### ISSUE TITLE
Easy Bootstrapping

### ISSUE THREAD

**Issue by n00shie** [isovector/adventure#10]
As a user downloading the game, I'd like a method where all the dependencies and libraries will be installed automatically. I am not sure of the exact details, but can that be done in the make file?

**Comment by isovector** [comment]
That can't be done in the Makefile, and moreover, it's a significantly harder problem on Linux than on Windows. With so many different package managers out there, there is no one "right way" to package the files and have them work properly. 

Being said, we could probably pre-bake some .deb and .rpm's (and maybe a PKGBUILD for nerd points). However, this has a few problems: mainly that development is so fast that these packages would ALWAYS be out of date, and there are too few developers to devote any time to it.

`# apt-get install lua5.1 luarocks libsdl1.2-dev libsdl1.2debian libsdl-image1.2-dev libsdl-gfx1.2-dev libsdl-ttf1.2-dev imagemagick synfig` might do it for you though!

Thanks for your interest in adventure :). See you in three weeks!

**Comment by n00shie** [comment]
Fair enough (y). You might wanna add that line to the README

**Comment by isovector** [comment]
Did it work? I made up all of those packages.
